blueprint:
  name: Notify when outdoor temp > threshold and indoor == threshold
  description: >
    Sends a notification when:
    - Outdoor temperature exceeds a threshold
    - Indoor temperature equals the threshold
  domain: automation
  input:
    indoor_sensor:
      name: Indoor Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outdoor_sensor:
      name: Outdoor Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    threshold_value:
      name: Temperature Threshold
      description: The target temperature value (°C)
      default: 20.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.1
          mode: box
          unit_of_measurement: "°C"

    notify_service:
      name: Notification Service
      description: Enter full service ID (e.g. notify.pushover)
      selector:
        text:

    message_title:
      name: Notification Title
      default: "Indoor Equals Threshold, Outdoor Above"

    message_body:
      name: Notification Body
      default: >
        🌡️ Outdoor is {{ outdoor_temp }}°C (> {{ threshold }}°C),
        and indoor equals the threshold exactly ({{ indoor_temp }}°C).

trigger:
  - platform: template
    value_template: >
      {% set outside = states(!input outdoor_sensor) | float %}
      {% set threshold = !input threshold_value %}
      {{ outside > threshold }}

condition:
  - condition: template
    value_template: >
      {% set indoor = states(!input indoor_sensor) | float %}
      {% set threshold = !input threshold_value %}
      {{ indoor == threshold }}

action:
  - variables:
      indoor_temp: "{{ states(!input indoor_sensor) | float }}"
      outdoor_temp: "{{ states(!input outdoor_sensor) | float }}"
      threshold: !input threshold_value
  - service: "{{ !input notify_service }}"
    data:
      title: !input message_title
      message: !input message_body

mode: single
