blueprint:
  name: Notify when outside > inside and inside > threshold
  description: >
    Sends a notification when:
    - Outside temperature exceeds the current indoor temperature
    - Indoor temperature exceeds a user-defined threshold
  domain: automation
  input:
    indoor_sensor:
      name: Indoor Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outdoor_sensor:
      name: Outdoor Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    threshold_value:
      name: Temperature Threshold
      description: Only notify if inside temperature is above this
      default: 20.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.1
          mode: box
          unit_of_measurement: "°C"

    notify_service:
      name: Notification Service
      description: Enter full notify service ID (e.g. notify.pushover)
      selector:
        text:

    message_title:
      name: Notification Title
      default: "Indoor warmer than threshold, outdoor now warmer"

    message_body:
      name: Notification Body
      default: >
        🌡️ Outdoor is {{ outdoor_temp }}°C > indoor ({{ indoor_temp }}°C),
        and indoor > threshold ({{ threshold }}°C)

trigger:
  - platform: state
    entity_id: !input outdoor_sensor

  - platform: state
    entity_id: !input indoor_sensor

  - platform: numeric_state
    entity_id: !input indoor_sensor
    above: !input threshold_value

condition:
  - condition: template
    value_template: >
      {% set indoor = states(!input indoor_sensor) | float %}
      {% set outdoor = states(!input outdoor_sensor) | float %}
      {% set threshold = !input threshold_value %}
      {{ outdoor > indoor and indoor > threshold }}

action:
  - variables:
      indoor_temp: "{{ states(!input indoor_sensor) | float }}"
      outdoor_temp: "{{ states(!input outdoor_sensor) | float }}"
      threshold: !input threshold_value
      notify_service: !input notify_service
      message_title: !input message_title
      message_body: !input message_body

  - service: "{{ notify_service }}"
    data:
      title: "{{ message_title }}"
      message: "{{ message_body }}"

mode: single
