blueprint:
  name: Notify when outdoor > indoor and indoor > threshold
  description: >
    Sends a notification when:
    - Outdoor temperature is higher than indoor
    - Indoor temperature is above a set threshold
  domain: automation
  input:
    indoor_sensor:
      name: Indoor Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outdoor_sensor:
      name: Outdoor Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    threshold_value:
      name: Temperature Threshold
      description: Notify only if indoor is above this temperature
      default: 20.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.1
          mode: box
          unit_of_measurement: "°C"

    notify_service:
      name: Notification Service
      description: Enter full service ID (e.g. notify.pushover)
      selector:
        text:

    message_title:
      name: Notification Title
      default: "Indoor temp above threshold, outdoor now warmer"

    message_body:
      name: Notification Body
      default: >
        🌡️ Outdoor ({{ outdoor_temp }}°C) > indoor ({{ indoor_temp }}°C),
        and indoor > threshold ({{ threshold }}°C)

trigger:
  - platform: state
    entity_id: !input indoor_sensor
  - platform: state
    entity_id: !input outdoor_sensor

condition:
  - condition: template
    value_template: >
      {% set indoor = states[states('!input indoor_sensor')] | float %}
      {% set outdoor = states[states('!input outdoor_sensor')] | float %}
      {% set threshold = !input threshold_value %}
      {{ outdoor > indoor and indoor > threshold }}

action:
  - variables:
      indoor_temp: "{{ states(!input indoor_sensor) | float }}"
      outdoor_temp: "{{ states(!input outdoor_sensor) | float }}"
      threshold: !input threshold_value
  - service: !input notify_service
    data:
      title: !input message_title
      message: !input message_body

mode: single
